export interface Product {
  slug: string;
  name: string;
  brand: string;
  price: number;
  category: string;           // Main category (e.g. "Whole Foods", "Smartphones")
  subcategory?: string;       // Specific subcategory (exact match from wholeFoodsCategories)
  description: string;
  specs: string[];
  inStock: number;            // Fictitious stock units. Items with 0 are hidden from listings.
  rating: number;
  reviewCount: number;
  bestseller?: boolean;
  images: string[];
  colors?: string[];
  storage?: string[];
}

// Raw product data (source of truth - do not import directly in most places)
export const baseProductsData: Product[] = [
  {
    slug: "iphone-15-pro-titanium",
    name: "iPhone 15 Pro",
    brand: "Apple",
    price: 999,
    category: "Smartphones",
    description: "Titanium design. A17 Pro chip. The most advanced iPhone ever. Pro camera system with 5x Telephoto.",
    specs: ["6.1\" Super Retina XDR", "A17 Pro Chip", "48MP Main Camera", "Up to 29 hours video"],
    inStock: 142,
    rating: 4.9,
    reviewCount: 2843,
    bestseller: true,
    images: ["/images/products/iphone-16-pro-titanium.jpg", "/images/products/peak-design-45l.jpg", "/images/products/anker-prime-powerbank.jpg"],
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
  },
  {
    slug: "dyson-v15-detect",
    name: "Dyson V15 Detect Absolute",
    brand: "Dyson",
    price: 749,
    category: "Smart Home",
    description: "Laser dust detection. 60-minute runtime. The most intelligent cordless vacuum.",
    specs: ["Laser Dust Detection", "60 min runtime", "HEPA filtration", "LCD screen"],
    inStock: 64,
    rating: 4.8,
    reviewCount: 756,
    bestseller: true,
    images: ["/images/products/dyson-v15-detect.jpg", "/images/products/dyson-airwrap.jpg"],
  },
  {
    slug: "oura-ring-gen3",
    name: "Oura Ring Gen3",
    brand: "Oura",
    price: 299,
    category: "Wearables",
    description: "The most advanced health and wellness wearable. 24/7 heart rate, sleep tracking, readiness score, and recovery insights.",
    specs: ["Titanium construction", "7-day battery", "Sleep + Readiness scoring", "Waterproof"],
    inStock: 312,
    rating: 4.7,
    reviewCount: 1342,
    bestseller: true,
    images: ["/images/products/oura-ring-gen3-stealth.jpg", "/images/products/apple-watch-ultra-2.jpg"],
    colors: ["Stealth", "Silver", "Gold"],
  },
  {
    slug: "peak-design-travel-backpack-45l",
    name: "Travel Backpack 45L",
    brand: "Peak Design",
    price: 229,
    category: "Accessories",
    description: "The ultimate travel backpack. Designed for photographers and travelers who demand the best.",
    specs: ["45L capacity", "Weatherproof", "Camera cube compatible", "Laptop sleeve"],
    inStock: 89,
    rating: 4.9,
    reviewCount: 423,
    bestseller: true,
    images: ["/images/products/peak-design-45l.jpg"],
  },
  {
    slug: "bose-quietcomfort-ultra",
    name: "Bose QuietComfort Ultra Headphones",
    brand: "Bose",
    price: 429,
    category: "Wearables",
    description: "World-class noise cancelling headphones with premium sound and all-day comfort.",
    specs: ["Industry-leading ANC", "24-hour battery", "Premium materials", "Spatial audio"],
    inStock: 156,
    rating: 4.6,
    reviewCount: 892,
    bestseller: true,
    images: ["/images/products/bose-quietcomfort-ultra.jpg"],
  },
  {
    slug: "galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    price: 1299,
    category: "Smartphones",
    description: "The ultimate Android flagship with S Pen, 200MP camera, and titanium frame.",
    specs: ["6.8\" Dynamic AMOLED", "200MP Camera", "S Pen included", "Titanium frame"],
    inStock: 78,
    rating: 4.8,
    reviewCount: 1247,
    images: ["/images/products/galaxy-s24-ultra.jpg"],
    storage: ["256GB", "512GB", "1TB"],
  },
  {
    slug: "whoop-4-0",
    name: "Whoop 4.0",
    brand: "Whoop",
    price: 239,
    category: "Wearables",
    description: "Advanced fitness and recovery tracking worn on the wrist or bicep.",
    specs: ["Continuous HRV", "Sleep tracking", "Strain score", "30-day battery"],
    inStock: 203,
    rating: 4.5,
    reviewCount: 634,
    images: ["/images/products/whoop-4-0.jpg"],
  },
  {
    slug: "sonos-arc-ultra",
    name: "Sonos Arc Ultra",
    brand: "Sonos",
    price: 999,
    category: "Smart Home",
    description: "Premium Dolby Atmos soundbar for the ultimate home theater experience.",
    specs: ["Dolby Atmos", "14 drivers", "Voice control", "WiFi + Bluetooth"],
    inStock: 45,
    rating: 4.7,
    reviewCount: 312,
    images: ["/images/products/sonos-arc-ultra.jpg"],
  },
  {
    slug: "anker-737-power-bank",
    name: "Anker Prime 27,650mAh Power Bank",
    brand: "Anker",
    price: 129,
    category: "Accessories",
    description: "High-capacity portable charger with 140W output and smart display.",
    specs: ["27,650mAh", "140W output", "Smart digital display", "3 ports"],
    inStock: 167,
    rating: 4.8,
    reviewCount: 589,
    images: ["/images/products/anker-prime-powerbank.jpg"],
  },
  // ==================== WHOLE FOODS - FRUTAS & VERDURAS ====================
  // Using exact subcategory names from lib/categories.ts
  // Most items have ~80-120 fictitious stock. Items with 0 are hidden from the site.

  // FRUTAS
  {
    slug: "naranjas-valencianas",
    name: "Naranjas Valencianas",
    brand: "Umantai Orchards",
    price: 4.8,
    category: "Whole Foods",
    subcategory: "Naranja, Mandarina y Otros Cítricos",
    description: "Dulces y jugosas naranjas de la región de Valencia. Perfectas para zumo o consumo fresco.",
    specs: ["5kg caja", "Cultivo sostenible", "Alta en vitamina C", "Sin cera"],
    inStock: 0, // Hidden per request (example of 0 stock)
    rating: 4.7,
    reviewCount: 89,
    images: ["/images/products/naranjas-valencianas.jpg"],
  },
  {
    slug: "paltas-hass-premium",
    name: "Paltas Hass Premium",
    brand: "Umantai Orchards",
    price: 7.9,
    category: "Whole Foods",
    subcategory: "Paltas",
    description: "Paltas Hass de piel rugosa, cremosas y perfectas para guacamole o tostadas.",
    specs: ["Bandeja de 4 unidades", "Maduración controlada", "Origen Perú", "Ricas en grasas saludables"],
    inStock: 112,
    rating: 4.9,
    reviewCount: 312,
    bestseller: true,
    images: ["/images/products/paltas-hass-premium.jpg"],
  },
  {
    slug: "berries-mixtos-organicos",
    name: "Mix de Berries Orgánicos",
    brand: "Umantai Orchards",
    price: 9.5,
    category: "Whole Foods",
    subcategory: "Fresa, Arándano, Aguaymanto y Otros Berries",
    description: "Fresas, arándanos y aguaymanto orgánicos. Listos para smoothies, postres o consumo directo.",
    specs: ["500g bandeja", "Certificado orgánico", "Sin pesticidas", "Congelables"],
    inStock: 87,
    rating: 4.8,
    reviewCount: 204,
    images: ["/images/products/berries-mixtos-organicos.jpg"],
  },
  {
    slug: "platano-organico",
    name: "Plátano Orgánico",
    brand: "Umantai Orchards",
    price: 3.2,
    category: "Whole Foods",
    subcategory: "Plátano y Uva",
    description: "Plátanos maduros, dulces y energéticos. Ideales para smoothies o como snack natural.",
    specs: ["Racimo de 6-7 unidades", "Cultivo orgánico", "Alta en potasio", "Empaque biodegradable"],
    inStock: 145,
    rating: 4.6,
    reviewCount: 78,
    images: ["/images/products/platano-organico.jpg"],
  },
  {
    slug: "mango-kent",
    name: "Mango Kent",
    brand: "Umantai Orchards",
    price: 5.4,
    category: "Whole Foods",
    subcategory: "Melocotón, Durazno y Mango",
    description: "Mangos Kent jugosos y dulces, perfectos para ensaladas, postres o comer frescos.",
    specs: ["2kg bolsa", "Punto óptimo de madurez", "Sin conservantes", "Origen Piura"],
    inStock: 63,
    rating: 4.8,
    reviewCount: 134,
    images: ["/images/products/mango-kent.jpg"],
  },

  // VERDURAS
  {
    slug: "tomates-cherry-organicos",
    name: "Tomates Cherry Orgánicos",
    brand: "Umantai Gardens",
    price: 4.2,
    category: "Whole Foods",
    subcategory: "Tomate, Pepino y Pimiento",
    description: "Tomates cherry dulces y explosivos en sabor. Ideales para ensaladas y snacks.",
    specs: ["500g bandeja", "Cultivo hidropónico", "Sin pesticidas", "Listos para consumir"],
    inStock: 98,
    rating: 4.7,
    reviewCount: 156,
    images: ["/images/products/tomates-cherry-organicos.jpg"],
  },
  {
    slug: "espinaca-fresca",
    name: "Espinaca Fresca Baby",
    brand: "Umantai Gardens",
    price: 3.8,
    category: "Whole Foods",
    subcategory: "Lechuga, Espinaca y Hojas Verdes",
    description: "Hojas de espinaca baby tiernas y nutritivas. Perfecta para ensaladas y salteados.",
    specs: ["250g bolsa", "Lavada y lista para usar", "Alta en hierro y vitaminas", "Empaque compostable"],
    inStock: 120,
    rating: 4.5,
    reviewCount: 67,
    images: ["/images/products/espinaca-fresca.jpg"],
  },
  {
    slug: "brocoli-organico",
    name: "Brócoli Orgánico",
    brand: "Umantai Gardens",
    price: 4.6,
    category: "Whole Foods",
    subcategory: "Brócoli, Coliflor, Alcachofa y Col",
    description: "Brócoli fresco y compacto. Excelente fuente de fibra y antioxidantes.",
    specs: ["Unidad ~500g", "Cultivo orgánico", "Sin OGM", "Ideal al vapor o salteado"],
    inStock: 74,
    rating: 4.6,
    reviewCount: 92,
    images: ["/images/products/brocoli-organico.jpg"],
  },
  {
    slug: "zanahorias-arcoiris",
    name: "Zanahorias Arcoíris",
    brand: "Umantai Gardens",
    price: 3.9,
    category: "Whole Foods",
    subcategory: "Zanahoria, Beterraga, Rabanito y Otras Raíces",
    description: "Zanahorias de colores (naranja, morada, amarilla). Dulces y crujientes.",
    specs: ["500g bolsa", "Variedad de colores", "Ricas en betacarotenos", "Sin lavar"],
    inStock: 105,
    rating: 4.8,
    reviewCount: 118,
    images: ["/images/products/zanahorias-arcoiris.jpg"],
  },
  {
    slug: "haba-fresca",
    name: "Haba Fresca",
    brand: "Umantai Gardens",
    price: 5.1,
    category: "Whole Foods",
    subcategory: "Arveja, Vainita, Haba y Otras Legumbres",
    description: "Habas frescas de temporada, tiernas y llenas de proteína vegetal.",
    specs: ["500g bolsa", "De temporada", "Peladas a mano", "Ideal para guisos y ensaladas"],
    inStock: 0, // Hidden per request (Haba example)
    rating: 4.4,
    reviewCount: 31,
    images: ["/images/products/haba-fresca.jpg"],
  },
  {
    slug: "verduras-orientales-mix",
    name: "Mix Verduras Orientales",
    brand: "Umantai Gardens",
    price: 6.8,
    category: "Whole Foods",
    subcategory: "Verduras Orientales",
    description: "Selección de verduras orientales frescas: bok choy, pak choi, brotes y más.",
    specs: ["400g bandeja", "Lista para saltear", "Sabor auténtico asiático", "Cultivo controlado"],
    inStock: 0, // Hidden per request (Verduras Orientales example)
    rating: 4.3,
    reviewCount: 44,
    images: ["/images/products/verduras-orientales-mix.jpg"],
  },
  {
    slug: "lechuga-romana-crujiente",
    name: "Lechuga Romana Crujiente",
    brand: "Umantai Gardens",
    price: 2.9,
    category: "Whole Foods",
    subcategory: "Lechuga, Espinaca y Hojas Verdes",
    description: "Lechuga romana fresca y crujiente. Base perfecta para ensaladas César.",
    specs: ["Unidad grande", "Hidropónica", "Sin tierra", "Larga vida útil"],
    inStock: 89,
    rating: 4.5,
    reviewCount: 53,
    images: ["/images/products/lechuga-romana-crujiente.jpg"],
  },
  {
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    price: 799,
    category: "Wearables",
    description: "The most rugged and capable Apple Watch, built for endurance athletes.",
    specs: ["49mm titanium case", "36-hour battery", "Precision dual-frequency GPS", "Bright display"],
    inStock: 93,
    rating: 4.8,
    reviewCount: 987,
    images: ["/images/products/apple-watch-ultra-2.jpg"],
  },
  {
    slug: "galaxy-buds3-pro",
    name: "Galaxy Buds3 Pro",
    brand: "Samsung",
    price: 249,
    category: "Wearables",
    description: "Premium wireless earbuds with AI features and excellent sound.",
    specs: ["AI features", "ANC", "360 Audio", "IP57 water resistance"],
    inStock: 134,
    rating: 4.5,
    reviewCount: 412,
    images: ["/images/products/galaxy-buds3-pro.jpg"],
  },
  {
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    price: 999,
    category: "Smartphones",
    description: "The ultimate Google phone with best-in-class AI and photography.",
    specs: ["6.8\" LTPO OLED", "50MP camera", "Tensor G3", "7 years of updates"],
    inStock: 67,
    rating: 4.7,
    reviewCount: 756,
    images: ["/images/products/google-pixel-8-pro.jpg"],
  },
];

export { mainCategories as categories } from "./categories";

export const brands = [
  "Apple", "Samsung", "Dyson", "Oura", "Bose", "Peak Design", "Google", "Anker", 
  "Blue Bottle", "Patagonia", "Whoop", "Sonos", "Umantai Orchards", "Umantai Gardens"
];

// =====================================================
// Admin-aware exports (recommended for most of the app)
// These automatically include any price/stock changes made in /admin
// =====================================================
export {
  getAllProducts,
  getAvailableProducts,
  getProductBySlug,
  getBestsellers,
} from './adminProductStore';

// Raw base data (used by admin panel to show original values)
export { baseProductsData as baseProducts };
